services:
  db:
    image: postgres:15
    container_name: dvdrental_postgres

    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: dvdrental_streamlit

    depends_on:
      - db

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - .:/app

volumes:
  postgres_data: